# Generated by Django 5.0.3 on 2024-03-14 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('software issues', 'software issues'), ('other', 'other')], default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='project_topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reporting_manager', models.CharField(choices=[('Anurag', 'Anurag'), ('Samip', 'Samip'), ('Chirag', 'Chirag')], default='', max_length=200)),
                ('discussed_with_rm', models.BooleanField()),
                ('message', models.CharField(max_length=460)),
                ('attached_file', models.FileField(upload_to='uploads/')),
                ('project_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.project_issue')),
                ('project_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.project_topic')),
            ],
        ),
    ]
