# Generated by Django 5.0.3 on 2024-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_issue',
            name='issue_type',
            field=models.CharField(max_length=200),
        ),
    ]
