# Generated by Django 5.0.3 on 2024-03-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_feedback_history_reporting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_history',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
